(function () {
	var translations = {
	    "TakePicture": "Prenez une photo de carte de visite",
	    "Lookup": "Download Lookup Data",
	    "LookupConfirmed": "Do you want to pull the updated data?",
	    "LookupDataDownloaded": "Lookup data downloaded successfully",
	    "Minlookupval": "Min. 3 characters required",
	    "OfflineDb": "You are using offline database",
	    "BarCodeContent": "You are using embedded barcode content",
	    "Ok": "Ok",
	    "Next": "Suivant",
	    "Back": "Retour",
	    "Overview": "Vue d'ensemble",
	    "Comments": "commentaires",
	    "AssignTo": "Attribuer à:",
	    "Telemarketing": "Qualification de télémarketing",
	    "EmailOptin": "Oui, je souhaite recevoir de plus amples informations auprès par email",
	    "Settings": "réglages",
	    "EditRespMsg": "Les réponses peuvent être modifiés tant qu'ils n'ont pas été envoyés à télécharger sur le serveur. Ajouts doivent être déclenchées manuellement en cliquant sur \"réponses upload \"",
	    "SurveyList": "Liste d'enquête",
	    "UploadRespWeb": "Téléchargez réponses (Web)",
	    "UploadRespLocal": "Téléchargez réponses (local)",
	    "ChangeServer": "Changer de serveur local",
	    "EditResponses": "Modifier réponses",
	    "Logout": "Déconnexion",
	    "ThankYou": "Merci",
	    "ThankYouMsg": "Merci beaucoup d'avoir pris part à l'enquête.",
	    "Restart": "redémarrez",
	    "EditRespMsgRsp": "Les réponses ne peuvent être modifiés tant qu'ils n'ont pas été envoyés à télécharger sur le serveur. Tous les dossiers téléchargés avec succès disparaîtront de l'écran. <br />",
	    "UserResponses": "Les réponses des utilisateurs",
	    "Login": "Connexion",
	    "Email": "Email",
	    "Password": "mot de passe",
	    "Resources": "ressources",
	    "Comment": "commenter",
	    "History": "histoire",
	    "YourEmail": "votre e-mail",
	    "RespHistory": "Histoire de réponse",
	    "From": "à partir de",
	    "To": "pour",
	    "RespCount": "Nombre de réponses:",
	    "SavedOn": "Saved on",
	    "Status": "statut",
	    "Filter": "Filtrez",
	    "SurveyList": "Liste d'enquêtes",
	    "Refresh": "Actualiser",
	    "SelectOne": "Sélectionnez l'une ...",
	    "Questions": "Questions",
	    "Documents": "documents",
	    "Contact": "Contactez",
	    "MsgValidEmail": "S'il vous plaît entrer une adresse email valide.",
	    "PleaseWait": "S'il vous plaît patienter ...",
	    "LoginError": "Connectez erreur: {0}",
	    "UploadInPrg": "Téléchargez en cours",
	    "UploadFailed": "Impossible de télécharger réponse au serveur.",
	    "InvalidIp": "IP non valide",
	    "DownloadFailed": "Impossible de télécharger enquête.",
	    "SurveyDownloaded": "Enquête téléchargé avec succès",
	    "ImageSaved": "L'image a été sauvegardée avec succès",
	    "ImageNotSaved": "Impossible d'enregistrer l'image.",
	    "CameraFailed": "Caméra échoué: {0}",
	    "SavingRespFailed": "Un problème s'est produit lors de l'enregistrement réponse",
	    "ReviewQuestion": "Vous n'avez pas répondu à quelques questions obligatoires, s'il vous plaît des questions d'examen.",
	    "QuestionRequired": "S'il vous plaît donner une réponse à cette question",
	    "UploadingResponse": "Téléchargement réponse de l'utilisateur ...",
	    "PreparingResp": "Réponse Préparation pour le téléchargement",
	    "UploadingImage": "Image de la carte de Téléchargement {0} de {1}",
	    "UploadingText": "Fichiers texte Téléchargement de {0} de {1}",
	    "DownloadingRes": "Téléchargement de ressources {0} {0}",
	    "Uploaded": "envoyé",
	    "NotUploaded": "pas téléchargé",
	    "ConfirmSave": "Voulez-vous enregistrer vos réponses? \ NPour revoir vos réponses sur Annuler.",
	    "EnterIp": "S'il vous plaît taper l'adresse IP du serveur local",
	    "Failed": "manqué",
	    "SurveyDownloadFailed": "Impossible de télécharger des ressources requises par l'enquête. S'il vous plaît essayer de nouveau ce dernier.",
	    "ConfirmRefresh": "Toutes les enquêtes téléchargés seront supprimés, mais la réponse de l'utilisateur seront intacts. Voulez-vous rafraîchir?",
	    "GoToSettings": "Si vous êtes au milieu de votre enquête progression sera perdue. Voulez-vous continuer?",
        "CheckInternet": "Please connect to internet to get the latest survey list",
        "CheckInternetLookup": "Please connect to internet to get the lastest data",
        "OfflineMode": "Offline Data"
	}

	langMgr.setTranslation("FR", translations);
})();
