(function(){
	var translations = {
		"TakePicture": "Visitenkarte fotografieren",
		"Save": "Speichern",
		"Lookup": "Kontaktdatenbank herunterladen",
		"LookupConfirmed": "Wollen Sie die aktuellste Kontaktdatenbank herunterladen?\nDies ermöglicht die Verwendung der Suchfunktionen ohne Internetverbindung.",
		"LookupDataDownloaded": "Die Kontaktdatenbank erfolgreich heruntergeladen.",
		"Minlookupval": "Bitte mindestens 3 Zeichen eingeben!",
		"OfflineDb": "Kontakt wurde aus Offline-Datenbank importiert.",
		"OnlineDb": "Kontakt wurde aus Online-Datenbank importiert.",
		"BarCodeContent": "Kontaktdaten aus Barcode verwendet.",
		"ForgotPassword": "Passwort vergessen?",
		"OverwriteContact": "Bereits eingetragene Kontaktinformationen werden beim Import überschrieben. Möchten Sie fortfahren?",
		"SelectContact": "Bitte einen Kontakt zum Import auswählen.",
		"Ok": "OK",
		"Next": "Weiter",
		"Back": "Zurück",
		"Overview": "Übersicht",
		"Comments": "Kommentare",
		"AssignTo": "Weiterleiten an:",
		"Telemarketing": "Telemarketing Follow-Up",
		"EmailOptin": "Ja, Ich möchte weitere Informationen per E-Mail erhalten.",
		"Settings": "Einstellungen / Upload",
		"EditRespMsg": "Noch nicht an den Server übermittelte Daten können editiert werden. Zum Upload der Daten bitte den Menüpunkt \"Upload Kontakte\" aufrufen.",
		"UploadRespWeb": "Kontakte hochladen",
		"UploadRespLocal": "Alternativer Server",
		"ChangeServer": "Alt. Server einrichten",
		"EditResponses": "Kontakte bearbeiten",
		"Logout": "Abmelden",
		"ThankYou": "Danke",
		"ThankYouMsg": "Vielen Dank, dass Sie den Fragebogen ausgefüllt haben.",
		"Restart": "Neuen Kontakt erfassen.",
		"EditRespMsgRsp": "Erfasste Kontakte und Antworten können nachbearbeitet werden, solange sie noch nicht an den Server übermittelt wurden. Erfolgreich hochgeladene Datensätze werden nach dem Upload nicht mehr angezeigt. <br />",
		"UserResponses": "Noch nicht übermittelte Kontakte",
		"Login": "Anmelden",
		"Email": "E-Mail",
		"Password": "Kennwort",
		"Resources": "Ressourcen",
		"Comment": "Anmerkung",
		"History": "Verlauf",
		"YourEmail": "Ihre E-Mail",
		"RespHistory": "Status erfasste Kontakte",
		"From": "Von",
		"To": "Bis",
		"RespCount": "Anzahl Kontakte:",
		"SavedOn": "Zeitstempel (Speicherzeitpunkt)",
		"Status": "Status",
		"Filter": "Filtern",
		"SurveyList": "Übersicht Fragebögen",
		"Refresh": "Aktualisieren",
		"SelectOne": "Bitte auswählen…",
		"Questions": "Fragen",
		"Documents": "Dokumente",
		"Contact": "Kontakt",
		"MsgValidEmail": "Bitte geben Sie eine gültige E-Mail-Adresse ein.",
		"PleaseWait": "Bitte haben Sie einen Moment Geduld…",
		"LoginError": "Fehler beim Login: {0}",
		"ForgotPasswordError": "Fehler in der \"Passwort vergessen\"-Funktion: {0}",
		"ResetPass": "Sie erhalten in Kürze eine E-Mail mit Anweisungen zur Wiederherstellung des Passwortes.",
		"UserNotExists": "User existiert nicht.",
		"UploadInPrg": "Daten werden übertragen",
		"UploadFailed": "Kontakte konnten nicht an den Server übertragen werden.",
		"InvalidIp": "Ungültige IP-Adresse",
		"DownloadFailed": "Fragebogen konnte nicht geladen werden.",
		"SurveyDownloaded": "Der Fragebogen wurde heruntergeladen.",
		"ImageSaved": "Das Bild wurde gespeichert.",
		"ImageNotSaved": "Das Bild konnte nicht gespeichert werden.",
		"CameraFailed": "Fehler in der Kamerafunktion: {0}",
		"SavingRespFailed": "Fehler beim Speichern der Antworten.",
		"ReviewQuestion": "Sie haben noch wenigen erforderlichen Fragen beantwortet haben, bitte Fragen zu beantworten.",
		"QuestionRequired": "Bitte beantworten Sie alle Pflichtfragen.",
		"UploadingResponse": "Datensätze werden an Server übertragen...",
		"PreparingResp": "Daten werden für Upload vorbereitet",
		"UploadingImage": "Upload von Foto {0} von {1}",
		"UploadingText": "Upload von Textinhalten {0} von {1}",
		"DownloadingRes": "Herunterladen Ressourcen {0} von {0}",
		"Uploaded": "Hochgeladen",
		"NotUploaded": "Nicht hochgeladen",
		"ConfirmSave": "Wollen Sie den Fragebogen abschließen?\nUm die Antworten noch einmal zu bearbeiten, klicken Sie \"Review\".",
		"EnterIp": "Bitte geben Sie die IP-Adresse des alternativen Servers ein.",
		"Failed": "Fehler",
		"SurveyDownloadFailed": "Der Fragebogen konnte nicht vollständig geladen werden. Bitte versuchen Sie es später noch einmal.",
		"ConfirmRefresh": "Möchten Sie die Liste aktualisieren?\nAlle heruntergeladenen Fragebögen werden gelöscht. Noch nicht übertragene Kontakte bleiben aber erhalten.",
		"GoToSettings": "Möchten Sie den aktuellen Fragebogen verwerfen? Wenn Sie bereits Daten erfasst haben, schließen Sie den Bogen vorher ab, um die Eingaben zu speichern.",
		"CheckInternet": "Zum Aktualisieren der verfügbaren Fragebögen bitte eine Internetverbindung herstellen.",
		"CheckInternetLookup": "Zum Aktualisieren der aktuellen Kontaktdatenbank bitte eine Internetverbindung herstellen.",
		"OfflineMode": "Offline-Daten",
		"MailProblem": "Fehler beim Senden der E-Mail",
		"UploadSuccess": "Daten wurden erfolgreich übertragen.",
		"CheckInternetUpload": "Upload der Daten nicht möglich. Bitte prüfen Sie ob eine Internetverbindung besteht.",
		"InvalidUserPassword": "Ungültiger Benutzername oder Passwort",
		"EmptyServerDetail": "Keine Servereinstellungen",
		"ClearContact": "Datensatz leeren",
		"NewContact": "Neuer Kontakt",
		"ChangeSurvey": "Fragebogen wechseln",
		"ConnectionTimeOut": "Server antwortet nicht. Bitte prüfen Sie, ob eine Internetverbindung besteht.",
		"ConnectionError": "Verbindungsfehler. Bitte prüfen Sie, ob eine Internetverbindung besteht.",
		"SurveyListError": "Fehler beim Laden der Fragbogenauswahl.",
		"AudioSaved": "Die Aufnahme wurde gespeichert.",
		"AudioNotSaved": "Fehler beim Speichern der Aufnahme.",
		"Extracontactinfo": "Kontaktdaten ergänzen",
		"Conclude": "Fragebogen abschließen",
		"Retake": "Neues Foto",
		"ImageUploadedIinfo": "Kontaktinformationen werden vom Back-Office-Team erfasst.",
		"DbDownload":"Datenbank herunterladen",
		"ContactForm":"Kontaktformular",
		"BadgeScan":"Visitenkarten Scan",
		"LookUp":"Suche",
		"CommentTab": "Kommentar",
		"ContactTab": "Kontakt",
		"QuestionTab": "Fragen",
		"PendMsg": "Alle Kontakte hochgeladen",
		"PendMsgCount": "Bitte hochladen: {0} ausstehend",
		"Cancel": "Abbrechen",
		"loggedInAs": "angemeldet als",
		"DataDownloaded":"Daten heruntergeladen",
		"RequestData": "Requesting data from server",
		"Yes": "Ja",
		"ResponseDelete": "Antwort(en) wurden gelöscht",
		"ResponseDeleteRequired": "Bitte mindestens einen Eintrag auswählen",
		"ConfrimResponseDelete": "Markierte Einträge löschen?",
	}

	langMgr.setTranslation("DE", translations);
})();