(function () {
	var translations = {
	    "TakePicture": "Tome la foto de la tarjeta de visita",
	    "Lookup": "Download Lookup Data",
	    "LookupConfirmed": "Do you want to pull the updated data?",
	    "LookupDataDownloaded": "Lookup data downloaded successfully",
	    "Minlookupval": "Min. 3 characters required",
	    "OfflineDb": "You are using offline database",
	    "BarCodeContent": "You are using embedded barcode content",
	    "Ok": "bueno",
	    "Next": "próximo",
	    "Back": "espalda",
	    "Overview": "visión de conjunto",
	    "Comments": "Comentarios",
	    "AssignTo": "Asignar a:",
	    "Telemarketing": "cualificación Telemarketing",
	    "EmailOptin": "Sí, me gustaría recibir más información por email",
	    "Settings": "Configuración",
	    "EditRespMsg": "Las respuestas pueden ser editadas, siempre y cuando no se han enviado para cargar en el servidor. Subidas deben ser disparado manualmente haciendo clic en \"Cargar la respuesta \"",
	    "SurveyList": "Lista Encuesta",
	    "UploadRespWeb": "Subir Respuestas (Web)",
	    "UploadRespLocal": "Subir respuestas (Local)",
	    "ChangeServer": "Cambiar servidor local",
	    "EditResponses": "Editar Respuestas",
	    "Logout": "Salir",
	    "ThankYou": "¡gracias",
	    "ThankYouMsg": "Muchas gracias por participar en la encuesta.",
	    "Restart": "reanudar",
	    "EditRespMsgRsp": "Las respuestas sólo pueden ser editadas, siempre y cuando no se han enviado para cargar en el servidor. Todos los registros cargados satisfactoriamente desaparecerán de la pantalla. <br />",
	    "UserResponses": "Las respuestas del usuario",
	    "Login": "login",
	    "Email": "Email",
	    "Password": "contraseña",
	    "Resources": "Recursos",
	    "Comment": "comentario",
	    "History": "historia",
	    "YourEmail": "Su correo electrónico",
	    "RespHistory": "Historia de Respuesta",
	    "From": "de",
	    "To": "a",
	    "RespCount": "Conteo de respuesta:",
	    "SavedOn": "Guardado en",
	    "Status": "estado",
	    "Filter": "Filtrar",
	    "SurveyList": "lista Encuesta",
	    "Refresh": "refrescar",
	    "SelectOne": "Seleccione uno ...",
	    "Questions": "Preguntas",
	    "Documents": "Documentos",
	    "Contact": "contacto",
	    "MsgValidEmail": "Por favor, introduzca un email válido.",
	    "PleaseWait": "Por favor, espere ...",
	    "LoginError": "Error de sesión: {0}",
	    "UploadInPrg": "Subir en curso",
	    "UploadFailed": "No se pudo cargar respuesta al servidor.",
	    "InvalidIp": "IP no válida",
	    "DownloadFailed": "No se pudo descargar Encuesta.",
	    "SurveyDownloaded": "Encuesta descargado con éxito",
	    "ImageSaved": "La imagen ha sido guardado con éxito",
	    "ImageNotSaved": "no pudo salvar la imagen.",
	    "CameraFailed": "Cámara Error: {0}",
	    "SavingRespFailed": "Algún problema ha ocurrido mientras que el ahorro respuesta",
	    "ReviewQuestion": "No ha respondido a algunas preguntas requeridas, por favor, las preguntas de repaso.",
	    "QuestionRequired": "Por favor, dar respuesta a esta pregunta",
	    "UploadingResponse": "Respuesta del Usuario Carga ...",
	    "PreparingResp": "Preparación para la respuesta de carga",
	    "UploadingImage": "Imagen de la carta Carga {0} de {1}",
	    "UploadingText": "Carga de archivos de texto {0} de {1}",
	    "DownloadingRes": "Descarga de recursos {0} de {0}",
	    "Uploaded": "Subida",
	    "NotUploaded": "No subido",
	    "ConfirmSave": "¿Quieres guardar sus respuestas? \ NPara revisar sus respuestas, pulse cancelar.",
	    "EnterIp": "Por favor, escriba la dirección IP del servidor local",
	    "Failed": "fracasado",
	    "SurveyDownloadFailed": "No se ha podido descargar un recurso requerido por la encuesta. Por favor, inténtelo de nuevo este último.",
	    "ConfirmRefresh": "Todas las encuestas descargados serán borrados pero la respuesta del usuario estará intacta. ¿Desea actualizar?",
	    "GoToSettings": "Si usted está en medio de la encuesta se perderá su progreso. ¿Desea continuar?",
        "CheckInternet": "Please connect to internet to get the latest survey list",
        "CheckInternetLookup": "Please connect to internet to get the lastest data",
        "OfflineMode": "Offline Data"
    }

	langMgr.setTranslation("ES", translations);
})();
