(function () {
	var translations = {
		"TakePicture": "Business Card Photo",
		"Save": "Save",
		"Lookup": "Download Look-Up Data",
		"LookupConfirmed": "Do you want to download the latest database to the device?\nDownloading the data will allow searches without internet connection.",
		"LookupDataDownloaded": "Look-up database downloaded successfully.",
		"Minlookupval": "Please enter at least 3 characters.",
		"OfflineDb": "Record imported from offline database.",
		"OnlineDb": "Record imported from online database.",
		"BarCodeContent": "Record imported from embedded barcode content.",
		"ForgotPassword": "Forgot Password?",
		"OverwriteContact": "Importing this record will overwrite any existing contact data. Do you want to continue?",
		"SelectContact": "Please select a contact to import!",
		"Ok": "OK",
		"Next": "Next",
		"Back": "Back",
		"Overview": "Overview",
		"Comments": "Comments",
		"AssignTo": "Assign To: ",
		"Telemarketing": "Telemarketing qualification",
		"EmailOptin": "Yes, I would like to receive further information per email",
		"Settings": "Settings / Upload",
		"EditRespMsg": "Responses can be edited as long as they have not been sent for upload to the server. Uploads need to be triggered manually by clicking \"Upload responses\"",
		"UploadRespWeb": "Upload Responses",
		"UploadRespLocal": "Alternative Routing",
		"ChangeServer": "Alt. Routing Settings",
		"EditResponses": "Edit Responses",
		"Logout": "Logout",
		"ThankYou": "Thank You",
		"ThankYouMsg": "Thank you very much for completing the questionnaire.",
		"Restart": "Enter New Contact",
		"EditRespMsgRsp": "Responses can only be edited as long as they have not been sent for upload to the server. All records uploaded successfully will disappear from this screen.<br />",
		"UserResponses": "Contacts Awaiting Upload",
		"Login": "Login",
		"Email": "Email",
		"Password": "Password",
		"Resources": "Resources",
		"Comment": "Comment&nbsp;&nbsp;",
		"History": "History",
		"YourEmail": "Your Email",
		"RespHistory": "Response History",
		"From": "From",
		"To": "To",
		"RespCount": "Number of responses:",
		"SavedOn": "Saved on",
		"Status": "Status",
		"Filter": "Filter",
		"SurveyList": "Survey List",
		"Refresh": "Refresh",
		"SelectOne": "Select one...",
		"Questions": "Questions",
		"Documents": "Documents",
		"Contact": "Contact",
		"MsgValidEmail": "Please enter a valid email.",
		"PleaseWait": "Please wait...",
		"LoginError": "Login Error: {0}",
		"ForgotPasswordError": "Forgot Password Error: {0}",
		"ResetPass": "An email with password reset instructions has been sent to your address.",
		"UserNotExists": "User does not exist.",
		"UploadInPrg": "Upload in progress",
		"UploadFailed": "Could not upload responses to server.",
		"InvalidIp": "Invalid IP address",
		"DownloadFailed": "Could not download survey.",
		"SurveyDownloaded": "Survey downloaded sucessfully.",
		"ImageSaved": "The image has been saved successfully.",
		"ImageNotSaved": "Could not save image.",
		"CameraFailed": "Camera Error: {0}",
		"SavingRespFailed": "A problem occured while saving response",
		"ReviewQuestion": "To conclude the questionnaire, please answer all mandatory questions. (To navigate to those, please use the \"Overview\" tab and select the questions marked in red.)",
		"QuestionRequired": "Please answer all mandatory questions.",
		"UploadingResponse": "Uploading user responses...",
		"PreparingResp": "Preparing responses for upload",
		"UploadingImage": "Uploading business card image {0} of {1}",
		"UploadingText": "Uploading text content {0} of {1}",
		"DownloadingRes": "Downloading resources {0} of {0}",
		"Uploaded": "Uploaded",
		"NotUploaded": "Not uploaded",
		"ConfirmSave": "Do you want to conclude and save this questionnaire?\nTo review your answers press \"Review\".",
		"EnterIp": "Please specify IP address of alternative server.",
		"Failed": "Failed",
		"SurveyDownloadFailed": "Failed to download all survey resources. Please try again later.",
		"ConfirmRefresh": "Do you want to refresh the survey list?\nAll downloaded surveys will be cleared but users' responses awaiting upload will be intact.",
		"GoToSettings": "Do you want to cancel the current questionnaire and open the settings menu?\nIf you have already entered information in the current questionnaire, please complete and save it first.",
		"CheckInternet": "Please connect to the internet to access the latest survey list.",
		"CheckInternetLookup": "Please connect to the internet to access the lastest data.",
		"OfflineMode": "Offline Data",
		"MailProblem": "Error: Email could not be sent.",
		"UploadSuccess": "All records were uploaded successfully.",
		"CheckInternetUpload": "Please connect to the internet to upload the response(s).",
		"InvalidUserPassword": "Invalid username or password",
		"EmptyServerDetail": "Empty server details",
		"ClearContact": "Reset Questionnaire",
		"NewContact": "New Contact",
		"ChangeSurvey": "Change Survey",
		"ConnectionTimeOut": "Connection time out.\nPlease check your internet connection.",
		"ConnectionError": "Check your internet connection.",
		"SurveyListError": "Couldn't get survey list.",
		"AudioSaved": "The recording has been saved successfully.",
		"AudioNotSaved": "Recording could not be saved.",
		"Extracontactinfo": "Add extra contact info",
		"Conclude": "Conclude",
		"Retake": "Retake photo",
		"ImageUploadedIinfo": "Contact data will be retrieved from photo by back office team.",
		"DbDownload":"Download database",
		"ContactForm":"Contact Form",
		"BadgeScan":"Badge Scan",
		"LookUp":"LookUp",
		"CommentTab": "Comment",
		"ContactTab": "Contact",
		"QuestionTab": "Question",
		"PendMsg": "All records uploaded",
		"PendMsgCount": "Please upload: {0} pending",
		"Cancel": "Cancel",
		"loggedInAs": "Logged in as",
		"DataDownloaded":"data downloaded",
		"RequestData": "Requesting data from server",
		"Yes": "Yes",
		"ResponseDelete": "Response(s) deleted successfully",
		"ResponseDeleteRequired": "Please select at least one response",
		"ConfrimResponseDelete": "Are you sure to delete?",
	}

	langMgr.setTranslation("EN", translations);
})();